spring.application.name=minimarket
# Configuraci�n de H2 en memoria
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true

# Configuraci�n de JPA e Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect


#JWT configuration
#jwt.secret=2XZCFnmx0gac60bn7LVsCtpxpT36eCKJBGEbXg3luFun
#jwt.expiration= 360000
